name: Run Appium Tests on Android Emulator

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Deployment message'
        required: true
        default: 'Run Appium tests'
        
jobs:
  appium-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Android SDK & Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_4
          disable-animations: true
          script: echo "Android emulator is ready."

      - name: Install Node.js (required for Appium)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Appium
        run: |
          npm install -g appium
          appium -v

      - name: Start Appium server in background
        run: |
          nohup appium > appium.log 2>&1 &
          sleep 10

      - name: Run Appium Tests
        run: |
           pytest --html=report.html --self-contained-html
