name: Appium Android Tests

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Deployment message'
        required: true
        default: 'Run appium tests'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm install -g appium
           
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        # Optional: Specify exact command line tools version
        cmdline-tools: 'latest'  # or '12.0' to match your preinstalled version

    - name: Accept licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        
    - name: Install Android packages
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "emulator" "system-images;android-33;google_apis;x86_64"
      
    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        arch: x86_64
        profile: Pixel XL
        disable-animations: true
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        script: |
          adb devices
          adb wait-for-device
          adb shell getprop init.svc.bootanim
          echo "Emulator is ready"

    - name: Start Appium server
      run: |
        appium --log-level error --relaxed-security &
        sleep 10
        adb devices
        echo "Appium server started"
        
    - name: Run tests
      run: |
        pytest --html=report.html

    - name: Upload html test report as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report
        path: report.html
